# Generated by Django 5.1.5 on 2025-02-10 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='postion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yeencears_of_exper', models.IntegerField()),
                ('discription', models.CharField(max_length=100)),
                ('postion_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postion_employees', to='employees.employees')),
            ],
        ),
    ]
